#ifndef __READ_SCRIPTS_DEBUG_SWITCH_H
#define __READ_SCRIPTS_DEBUG_SWITCH_H

#define READ_SCRIPTS_DEBUG   			1
#define READ_SCRIPTS_COMMAND_DEBUG   	1
#define READ_SCRIPTS_STATE_DEBUG        0
#define SCRIPTS_COMMAND_CONTEXT_DEBUG   0
#define LOAD_COMMAND_DEBUG				0

#endif
