#ifndef __M_FLASH_HANDLER_CONFIG_DEFAULT_H
#define __M_FLASH_HANDLER_CONFIG_DEFAULT_H

#define M_FLASH_BASIC_UNIT_IN_BYTES             4096
#define M_FLASH_ENABLE_BOUNDARY_CHECK			1
#define M_FLASH_MULTI_PARTITION                 1

#define USE_MY_FLASH_EVENT_HANDLER_DEBUG		1
#endif
