#ifndef __M_PRIORITY_QUEUES_CONFIG_DEFAULT_H
#define __M_PRIORITY_QUEUES_CONFIG_DEFAULT_H

#define USE_MY_PRIORITY_QUEUE_DEBUG                  0
#define MAX_PRIORITY_QUEUE_DEBUG_ID_COUNT            5

#define MY_PRIORITY_QUEUE_MAX_NODE_NUMBER					20
#define MAX_PRIORITY_QUEUE_COUNT     				 		MY_PRIORITY_QUEUE_MAX_NODE_NUMBER
#define LIST_NODE_TABLE_SIZE         						10

#define BIT_COUNT_IN_UINT32									32 // necessary?
#define TYPE_DEF_PRIORITY_TABLE_VALUE						uint32_t

#endif
